---
- name: Render Multiple Files
  hosts: bom02
  vars:
    env: STATGING
    uname: Remo
    username: rmo
    email: rmo@example.com
  tasks:
    - name: copy files
      template:
        src: "{{ item }}"
        dest: $HOME/data/{{ item[:-2] }}conf
      loop:
       - os_distro.j2 
       - httpd.j2
       - gitconfig_temp.j2
...
