- hosts: bom02
  name: update ubuntu packages
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Check if reboot is needed
      stat:
         path: /var/run/reboot-required
      register: st
    - name: Reboot Server
      command: reboot
      when: st.stat.exists
