---
- name: Create Prometheus
  hosts: bom02
  become: yes
  tasks:
   - name: Create Prometheus group
     group:
       name: prometheus 
     become: yes

   - name: Create Promethes user with non-login shell
     user:
       name: prometheus
       group: prometheus
       system: yes
       shell: "/sbin/nologin"
       comment: "nologin user"
       create_home: "no"
       state: present
...
