---
- name: Provision EC2
  hosts: localhost
  become: yes
  gather_facts: False

  vars_files:
    - group_vars/all

  tasks:
    - name: Create EC2 Insyance
      ec2:
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        key_name: "{{ ec2_keypair }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        wait: true
        region: "{{ ec2_region }}"
        count: "{{ ec2_instance_count }}"
        count_tag:
           Name: Demo
        instance_tags:
           Name: Demo
        vpc_subnet_id: subnet-c36745ab
        assign_public_ip: yes
        wait: true
      register: ec2
...
