---
- name: Provision Amazon EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false ;Ansible will not run setup module
  
  vars_files:
   - group_vars/all

  tasks:
   - pip:
      name: boto3
      executable: pip3
     become: true
   - name: Launch webserver
     ec2:
       access_key: "{{ ec2_access_key }}"
       secret_key: "{{ ec2_secret_key }}"
       keypair: "{{ ec2_keypair }}"
       group: "{{ ec2_security_group }}"
       type: "{{ ec2_instance_type }}"
       image: "{{ ec2_image }}"
       region: "{{ ec2_region }}"
       count: "{{ ec2_instance_count }}"
     register: ec2
...
