---
# tasks file for ec2-provision
- name: Basic Provisioning Example
  ec2:
    access_key: "{{ ec2_access_key }}"
    secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    count: "{{ ec2_instance_count }}"
    count_tag:
      Name: Demo
    instance_tags:
      Name: Demo
    vpc_subnet_id: subnet-c36745ab
    assign_public_ip: yes
    wait: true
  register: ec2
